name: '${APP_NAME:-MekCook}'
services:
  mekcook:
    build: .
    container_name: api
    ports:
      - '${APP_PORT:-8000}:8000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--require=tsconfig-paths/register

  mysql:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - database:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - './docker/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

volumes:
  database:
